services:
  payload:
    container_name: payload-cms
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '${PAYLOAD_PORT}:${PAYLOAD_PORT}'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    depends_on:
      - mongo
    env_file:
      - .env
    networks:
      - payload-net

  # Ensure your DB_URI uses 'mongo' as the hostname ie. mongodb://mongo/my-db-name
  mongo:
    container_name: '${DB_CONTAINER_NAME}'
    image: mongo:8.0.6
    ports:
      - '${DB_PORT}:${DB_PORT}'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - mongo-data:/data/db
    logging:
      driver: none
    env_file:
      - .env
    networks:
      - payload-net

volumes:
  mongo-data:
  node_modules:

networks:
  payload-net:
    driver: bridge