version: '3'

services:
  payload:
    container_name: payload-cms
    image: node:18-alpine
    ports:
      - '${PAYLOAD_PORT}:${PAYLOAD_PORT}'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: >
      sh -c "
        corepack enable && 
        corepack prepare pnpm@latest --activate && 
        pnpm install && pnpm dev
      "
    depends_on:
      - mongo
    env_file:
      - .env
    networks:
      - payload-net

  # Ensure your DATABASE_URI uses 'mongo' as the hostname ie. mongodb://mongo/my-db-name
  mongo:
    container_name: mongo-db
    image: mongo:latest
    ports:
      - '${MONGO_DB_PORT}:${MONGO_DB_PORT}'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - mongo-data:/data/db
    logging:
      driver: none
    env_file:
      - .env
    networks:
      - payload-net

volumes:
  mongo-data:
  node_modules:

networks:
  payload-net:
    driver: bridge